### ISSUE TITLE
Is there a reason why this plugin is deprecated?

### ISSUE THREAD

**Issue by zwindler** [rabbitmq/rabbitmq-management-visualiser#15]
Hi,

I've seen that this plugins is not shipped with RabbitMQ anymore. Is this a technical reason (bug or breaking change for example) or is it just because it's not deemed interesting enough?

I haven't tried it on the previous versions, but it seems like a great idea in my infrastructure. Is there a way to compile it/make it work on 3.7.x ? If so, can you give me additional guidelines even though I fully understand that it is not supported?

Regards
Denis GERMAIN

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
It was an experiment that was never fully fleshed out and went unmaintained many years ago.

**Comment by zwindler** [comment]
Thanks for the quick answer. 

And I'll post on rabbitmq-user next time.
